sudo: required

language: node_js
node_js:
  - '10.15.3'

services:
  - docker

script:
  - git clone https://github.com/MaximeMaillet/bank-operations-front.git src/front
  - cd src/front && npm i && npm run build
  - docker build -t deuxmax/bank-operations:latest .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push deuxmax/bank-operations:latest