version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ${STORAGE}/mongodb:/data/db

  grafana:
    restart: always
    image: grafana/grafana:latest
    volumes:
      - .data/grafana:/var/lib/grafana
    expose:
      - 3000
    ports:
      - 9988:3000