version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
      - 80:80
    volumes:
      - ./Docker/nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - front
      - api

  front:
    image: deuxmax/bank-operations-front:latest

  api:
    image: deuxmax/bank-operations-api:latest
    depends_on:
      - mongo
    environment:
      APP_PORT: 8080
      MONGO_HOST: mongodb://mongo:27017
      WAIT_HOSTS: mongo:27017
    links:
      - mongo
    volumes:
      - ${STORAGE}/keys:/var/app/keys

  mongo:
    image: mongo:latest
    volumes:
      - ${STORAGE}/mongodb:/data/db