version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
      - 8080:80
    volumes:
      - ./Docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - api

  api:
    build: .
    environment:
      APP_PORT: 8080
      MONGO_HOST: mongodb://mongo:27017
      WAIT_HOSTS: mongo:27017
    command: "npm run api-dev"
    links:
      - mongo
    volumes:
      - ${STORAGE}/keys:/var/app/keys
      - .:/var/app

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ${STORAGE}/mongodb:/data/db