version: '3'

networks:
  bank-nginx:
    external:
      name: ${NGINX_NETWORK_NAME}

  bank-mongo:
    external:
      name: ${MONGO_NETWORK_NAME}

services:
  nginx:
    image: nginx:1.15
    ports:
      - 8080:80
    volumes:
      - ./Docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/front/build:/var/app/
    networks:
      - bank-nginx

  api:
    build: .
    environment:
      APP_PORT: 8080
      MONGO_HOST: mongodb://mongo:27017
      WAIT_HOSTS: mongo:27017
      CORS_DOMAIN: ${CORS_DOMAIN}
    command: "npm run api-dev"
    networks:
      - bank-nginx
      - bank-mongo
    volumes:
      - ${STORAGE}/keys:/var/app/keys
      - .:/var/app

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ${STORAGE}/mongodb:/data/db
    networks:
      - bank-mongo