version: '3'
services:
  api:
    image: deuxmax/bank-operations:latest
    depends_on:
      - mongo
    environment:
      APP_PORT: 8080
      MONGO_HOST: mongodb://mongo:27017
      WAIT_HOSTS: mongo:27017
      CORS_DOMAIN: ${CORS_DOMAIN}
    links:
      - mongo
    volumes:
      - ${STORAGE}/keys:/var/app/keys

  mongo:
    image: mongo:latest
    volumes:
      - ${STORAGE}/mongodb:/data/db