version: '3'
services:
  api:
    build: .
    environment:
      APP_PORT: 8080
      MONGO_HOST: mongodb://mongo:27017
      WAIT_HOSTS: mongo:27017
      CORS_DOMAIN: ${CORS_DOMAIN}
    command: "npm run api-dev"
    ports:
      - 8080:8080
    links:
      - mongo
    volumes:
      - ${STORAGE}/keys:/var/app/keys
      - .:/var/app

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ${STORAGE}/mongodb:/data/db